---
abstract: 'A plugin for swig client'
author:
  - 'Logan Bell <logie@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Swig
requires:
  Dancer: 0
  Dancer::Config: 0
  Dancer::Test: 0
  Test::Easy: 0
  Test::Most: 0
  WebService::SwigClient: 0
resources:
  bugtracker: https://github.com/logie17/dancer-plugin-swig/issues
  repository: https://github.com/logie17/dancer-plugin-swig.git
version: 0.02
